services:
  allmon3:
    image: m8wat/allmon3:latest
    container_name: allmon3
    hostname: t5810-allmon3
    networks:
      allmon3:
        ipv4_address: 10.58.1.2
    ports:
      - 8008:80/tcp
    volumes:
      - "./etc/allmon3.ini:/etc/allmon3/allmon3.ini"
      - "./etc/users:/etc/allmon3/users"
    restart: unless-stopped

networks:
  allmon3:
    name: "allmon3_network"
    ipam:
      driver: default
      config:
        - subnet: 10.58.1.0/29